wandb_version: 1

max_len:
  desc: null
  value: 512
train_batch_size:
  desc: null
  value: 4
valid_batch_size:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 1.0e-05
epochs:
  desc: null
  value: 20
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.40.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715112226.0
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.11.3
      5: 0.16.6
      6: 4.40.0
      8:
      - 4
      - 5
      13: darwin-arm64
